import { PrismaClient } from '@prisma/client';
import { INDUSTRY } from '../../common/constants';

const prisma = new PrismaClient();

const tools = [
  {
    toolName: 'Nuke',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Adobe After Effects',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Blackmagic Fusion',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Autodesk Maya',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Blender',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Autodesk 3ds Max',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Houdini',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Adobe Substance Painter',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Foundry Mari',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'ZBrush (for sculpting/polypainting)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'ZBrush',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Houdini',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Autodesk Maya',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Adobe Photoshop',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Unreal Engine',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Unity',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VFX,
  },
  {
    toolName: 'Toon Boom Harmony',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_2D,
  },
  {
    toolName: 'Adobe Animate (formerly Flash)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_2D,
  },
  {
    toolName: 'TVPaint Animation',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_2D,
  },
  {
    toolName: 'Moho (formerly Anime Studio)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_2D,
  },
  {
    toolName: 'Clip Studio Paint',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_2D,
  },
  {
    toolName: 'Krita',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_2D,
  },
  {
    toolName: 'OpenToonz',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_2D,
  },
  {
    toolName: 'Synfig Studio',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_2D,
  },
  {
    toolName: 'Pencil2D',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_2D,
  },
  {
    toolName: 'Autodesk Maya',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_3D,
  },
  {
    toolName: 'Blender',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_3D,
  },
  {
    toolName: 'Cinema 4D',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_3D,
  },
  {
    toolName: 'Autodesk 3ds Max',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_3D,
  },
  {
    toolName: 'Houdini',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_3D,
  },
  {
    toolName: 'ZBrush (for character/prop sculpting)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.ANIMATION_3D,
  },
  {
    toolName: 'Unreal Engine',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VIRTUAL_PRODUCTION,
  },
  {
    toolName: 'Unity',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VIRTUAL_PRODUCTION,
  },
  {
    toolName: 'Autodesk Maya (for asset creation)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VIRTUAL_PRODUCTION,
  },
  {
    toolName: 'Houdini (for complex environments/FX)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VIRTUAL_PRODUCTION,
  },
  {
    toolName: 'Disguise',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VIRTUAL_PRODUCTION,
  },
  {
    toolName: 'Pixotope (media servers, real-time graphics)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VIRTUAL_PRODUCTION,
  },
  {
    toolName: 'Zero Density (virtual studio systems)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VIRTUAL_PRODUCTION,
  },
  {
    toolName: 'Mo-Sys (camera tracking)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VIRTUAL_PRODUCTION,
  },
  {
    toolName: 'OptiTrack',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VIRTUAL_PRODUCTION,
  },
  {
    toolName: 'Vicon (motion capture)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VIRTUAL_PRODUCTION,
  },
  {
    toolName: 'AJA',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VIRTUAL_PRODUCTION,
  },
  {
    toolName: 'Blackmagic Design (video I/O)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VIRTUAL_PRODUCTION,
  },
  {
    toolName: 'Unity',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VR,
  },
  {
    toolName: 'Unreal Engine',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VR,
  },
  {
    toolName: 'Blender (for 3D assets)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VR,
  },
  {
    toolName: 'Autodesk Maya (for 3D assets)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VR,
  },
  {
    toolName: 'Oculus Integration SDK',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VR,
  },
  {
    toolName: 'Meta Quest SDK',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VR,
  },
  {
    toolName: 'SteamVR Plugin',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VR,
  },
  {
    toolName: 'A-Frame (for web VR)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VR,
  },
  {
    toolName: 'Babylon.js (for web VR)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VR,
  },
  {
    toolName: 'Spatial Audio Tools',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.VR,
  },
  {
    toolName: 'Unity',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AR,
  },
  {
    toolName: 'Unreal Engine',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AR,
  },
  {
    toolName: 'ARKit (Apple)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AR,
  },
  {
    toolName: 'ARCore (Google)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AR,
  },
  {
    toolName: 'Vuforia',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AR,
  },
  {
    toolName: 'Spark AR Studio (Meta)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AR,
  },
  {
    toolName: '8th Wall (for WebAR)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AR,
  },
  {
    toolName: 'Zappar',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AR,
  },
  {
    toolName: 'Blender (for 3D assets)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AR,
  },
  {
    toolName: 'Adobe Aero',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AR,
  },
  {
    toolName: 'Unity',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Unreal Engine',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Blender',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Autodesk Maya',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Substance Painter (texturing)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'ZBrush (sculpting)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Adobe Photoshop (concept art, textures)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Adobe Illustrator (UI/vector art)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Perforce',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Git (version control)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Jira',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Trello (project management)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'FMOD',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Wwise (audio middleware)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Visual Studio',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'VS Code (coding IDEs)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GAME_DEV,
  },
  {
    toolName: 'Adobe After Effects',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.MOTION_DESIGN,
  },
  {
    toolName: 'Cinema 4D',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.MOTION_DESIGN,
  },
  {
    toolName: 'Adobe Illustrator',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.MOTION_DESIGN,
  },
  {
    toolName: 'Adobe Photoshop',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.MOTION_DESIGN,
  },
  {
    toolName: 'Adobe Premiere Pro',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.MOTION_DESIGN,
  },
  {
    toolName: 'Blender',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.MOTION_DESIGN,
  },
  {
    toolName: 'Mocha Pro',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.MOTION_DESIGN,
  },
  {
    toolName: 'LottieFiles',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.MOTION_DESIGN,
  },
  {
    toolName: 'Toon Boom Harmony',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.MOTION_DESIGN,
  },
  {
    toolName: 'Autodesk Maya',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.MOTION_DESIGN,
  },
  {
    toolName: 'Avid Pro Tools',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AUDIO_POST,
  },
  {
    toolName: 'Adobe Audition',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AUDIO_POST,
  },
  {
    toolName: 'Logic Pro X (macOS)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AUDIO_POST,
  },
  {
    toolName: 'Steinberg Cubase',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AUDIO_POST,
  },
  {
    toolName: 'Ableton Live',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AUDIO_POST,
  },
  {
    toolName: 'FMOD',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AUDIO_POST,
  },
  {
    toolName: 'Wwise',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AUDIO_POST,
  },
  {
    toolName: 'Izotope RX',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AUDIO_POST,
  },
  {
    toolName: 'Reaper',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AUDIO_POST,
  },
  {
    toolName: 'Audacity',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AUDIO_POST,
  },
  {
    toolName: 'Sonnox',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AUDIO_POST,
  },
  {
    toolName: 'Celemony Melodyne',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.AUDIO_POST,
  },
  {
    toolName: 'Agisoft Metashape',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.LIDAR,
  },
  {
    toolName: 'RealityCapture (Epic Games)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.LIDAR,
  },
  {
    toolName: 'Trimble Business Center',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.LIDAR,
  },
  {
    toolName: 'Inpho',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.LIDAR,
  },
  {
    toolName: 'Pix4D',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.LIDAR,
  },
  {
    toolName: 'CloudCompare',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.LIDAR,
  },
  {
    toolName: 'LAStools (LiDAR processing)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.LIDAR,
  },
  {
    toolName: 'Autodesk ReCap Pro',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.LIDAR,
  },
  {
    toolName: '3DF Zephyr',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.LIDAR,
  },
  {
    toolName: 'Meshroom (open-source)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.LIDAR,
  },
  {
    toolName: 'Bentley ContextCapture',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.LIDAR,
  },
  {
    toolName: 'Midjourney',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GENERATIVE_AI,
  },
  {
    toolName: 'DALL-E (OpenAI)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GENERATIVE_AI,
  },
  {
    toolName: 'Stable Diffusion',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GENERATIVE_AI,
  },
  {
    toolName: 'RunwayML',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GENERATIVE_AI,
  },
  {
    toolName: 'ChatGPT (OpenAI)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GENERATIVE_AI,
  },
  {
    toolName: 'DeepMotion (AI animation)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GENERATIVE_AI,
  },
  {
    toolName: 'Synthesia (AI video generation)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GENERATIVE_AI,
  },
  {
    toolName: 'ElevenLabs (AI voice generation)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GENERATIVE_AI,
  },
  {
    toolName: 'Topaz Labs (AI upscaling/enhancement)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GENERATIVE_AI,
  },
  {
    toolName: 'TensorFlow',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GENERATIVE_AI,
  },
  {
    toolName: 'PyTorch (ML frameworks for custom development)',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.GENERATIVE_AI,
  },
  {
    toolName: 'Python',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Git',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'GitHub',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'GitLab',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Perforce',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Jira',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Shotgun',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Ftrack',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Jenkins',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'CI/CD',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'GitHub Actions',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Visual Studio',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'VS Code',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'USD',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'OpenCue',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Deadline',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Docker',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Kubernetes',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'AWS',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Google Cloud Platform',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Azure',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'PySide',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'PyQt',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
  {
    toolName: 'Rez',
    isAddedByCompany: false,
    addedByCompanyID: null,
    industryName: INDUSTRY.PIPELINE,
  },
];

export async function seedTools() {
  console.log('🌱 Seeding tools...');
  try {
    for (const {
      toolName,
      isAddedByCompany,
      addedByCompanyID,
      industryName,
    } of tools) {
      await prisma.tool.upsert({
        where: { toolName },
        update: {},
        create: {
          toolName,
          isAddedByCompany,
          addedByCompanyID,
          industryName,
        },
      });
    }
    console.log(`✅ Successfully seeded ${tools.length} tools`);
  } catch (error) {
    console.error('❌ Error seeding tools:', error);
    throw error;
  }
}

if (require.main === module) {
  seedTools()
    .then(async () => {
      await prisma.$disconnect();
    })
    .catch(async (e) => {
      console.error(e);
      await prisma.$disconnect();
      process.exit(1);
    });
}
